[project]
name = "zmqcat"
version = "0.1.0"
description = "CLI tool for ZeroMQ stream inspection"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "zmq>=0.0.0",
]
